project:
  type: website
  output-dir: docs

website:
  title: "Text-as-Data - Course Website"
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "Text as Data: Introduction to Computational Text Analysis in R | Spring 2025 | University of Mannheim"  
  sidebar:
    background: "#8399B0"
    logo: "images/hex_sticker.png"
    pinned: true
    align: center
    tools:
      - icon: bank
        href: https://ilias.uni-mannheim.de/goto.php?target=crs_1589237&client_id=ILIAS
        text: Ilias
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: material.qmd
        text: Schedule, slides & materials
      - href: reading.qmd
        text: Text-as-Data literature
        
format:
  html:
    theme: 
      - default
      - css/theme.scss
    css: css/custom.css
    toc: true



