---
title: "Text-as-Data Datasets"
editor: 
  markdown: 
    wrap: 72
---

While we covered how to scrape text data on our own, there are also
great ready-to-use text datasets available. In the following, you find a
few examples:

-   [Manifesto Project Database](https://manifesto-project.wzb.eu/)

    -   **Description:** Collection of (partly) annotated party
        manifestos.

-   [ManifestoVault V1.0: Annotated full-text general election
    manifestos at the natural-sentence level of three European countries
    1970-2024](https://dataverse.nl/dataset.xhtml?persistentId=doi:10.34894/VKQSPO)

    -   **Description:** "Annotated full-text of national-level general
        election manifestos at a natural-sentence level of 43 political
        parties from Germany, Ireland, and the UK from 1970-2024. This
        repository aims to provide clean and accurate (as much as
        possible) full-text versions of election manifestos to
        facilitate all scholarly research for which parties’ election
        manifestos are relevant. More details on the structure of the
        dataset is found in the accompanying release note. (2024-12-06)"

<!-- -->

-   [ParlEE Dataverse](https://dataverse.harvard.edu/dataverse/ParlEE)

    -   **Description:** "The Parliamentary Emotive Expression (ParlEE)
        data sets provide full-text and scaled parliamentary plenary
        speeches for a selection of EU member state parliaments with the
        goal of supporting the development and application of text
        analysis approaches in political science."

-   [ParlLawSpeech](https://parllawspeech.org/data/)

    -   **Description:** "The ParlLawSpeech dataset offers *4.02 GB of
        data* in total, including machine-readable full texts of *43,582
        bills*, *28,124 laws*, and *3,092,431 plenary speeches* from
        eight European parliaments covering more than two decades each.
        ParlLawSpeech is meant to push the systematic analysis of
        European democracies with advanced text-as-data/NLP methods.
        Compared to the other excellent extant political science text
        corpora (cf. [Sebők et al.
        2025](https://doi.org/10.1177/01925121231199904)), it adds two
        key innovations. First, the bill and law corpora are are among
        the most encompassing full-text vectors of legal documents
        handled by parliaments. Second, we provide novel data linkage
        possibilities by offering a common identifier across bills,
        corresponding plenary speeches, and finally adopted laws-
        opening up new analytical opportunities to study the legislative
        process (basic ideas in the [tutorial
        section](https://parllawspeech.org/tutorials/))."

-   [EUSpeech v2](https://osf.io/c79ha/)

    -   **Description:** "Dataset of 11,466 Speeches by European PMs and
        Presidents (mostly between 2008-2020)."

-   [EU Commissioner speeches and Commission press
    releases](https://sites.google.com/site/christianrauh/data-and-resources)

    -   **Description**: "Full-text of corpus of all 13,618 speeches
        between 1985 and 2020 EU and full-text corpus of all 44,978
        press releases published between January 17, 1985, and January
        8, 2021."

    -   Part of the replication archives by Prof. Christian Rauh.

<!-- -->

-   [United Nations General Debate Corpus 1946 -
    2024](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/0TJX8Y)

    -   **Description:** "Every year since 1946, the General Debate has
        taken place at the beginning of the UN General Assembly session.
        Representatives from all UN member states deliver an address,
        discussing the issues they consider most important in global
        politics, revealing their governments’ positions, and seeking to
        persuade other states of their perspectives. The annual UN
        General Debate statements provide invaluable information for
        scholars of international relations – comparable globally and
        over time. However, these texts are stored as poor quality
        images without relevant metadata, preventing researchers from
        applying data science methods. This paper introduces the
        complete UN General Debate Corpus (UNGDC). Building on a
        previous incomplete release of UNGDC, we have extended the
        corpus to cover the entire 1946-present period, included
        additional data on all speakers, and provided advanced search
        and data visualisation tools on a [new
        website](https://www.ungdc.bham.ac.uk/). The complete corpus
        contains 10,952 speeches from 202 countries, including
        historical countries – making it the most comprehensive, unique,
        and accessible collection of global political speeches."

-   [Tweets by members of the U.S. Congress between 2009 and
    2019.](https://osf.io/pvb6d)

    -   And the accompanying paper: [Incivility Is Rising Among American
        Politicians on
        Twitter](https://journals.sagepub.com/doi/10.1177/19485506221083811)

    -   Close to 1.3 million tweets.

-   [Central banker speeches (CBS dataset)](https://cbspeeches.com/)

    -   The dataset features 35,487 unique speeches from 131 central
        banks, for the period going from the beginning of January
        1986 (date of the first online speech by a central bank) to the
        end of December 2023. Among those speeches, 5,347 were provided
        in a non-English language and were translated using Microsoft
        Translation services.

In addition, we can use tools provided by the university such as
**LexisNexis** (when in the university's wifi or VPN) to get access to
(historical) news articles: <https://dbis.ur.de/UBMAN/resources/1670>
