---
title: "Intro Session"
subtitle: "Week 01"
description: ""
author: ""
date: "Feb 11, 2025"
listing:
  - id: slides
    contents:
      - ../slides/week-01/*.qmd
    type: table
    fields: [title, subtitle, date]
    #date-format: "ddd, MMM DD"
    field-display-names:
      title: "Topic"
      subtitle: "Session"
      date: "Date"
    sort: [filename]
    sort-ui: false
    filter-ui: false
  # - id: assignments
  #   contents:
  #   type: table
  #   fields: [categories, title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     categories: "Assignment"
  #     title: "Title"
  #     date: "Due"
  #   sort: [date]
  #   sort-ui: false
  #   filter-ui: false
tbl-colwidths: [10,50,40]
editor: 
  markdown: 
    wrap: 72
---

# To Do's before our session

-   None. We will have an introductory session to get to know each
    other, go over the plan for the semester, and talk about both your
    and my expectations for the course.

-   Although our sessions are in the "Methodenlabor" and you will have
    access to computers, I encourage you to bring your own laptop (if
    you have one). That way, you can also work on assignments during the
    semester and the final examination at home. We will have time
    tomorrow to ensure everybody can install a working version of R and
    RStudio.

# Seminar slides

::: {#slides}
:::

# Materials

There are no materials for today's session.

However, below you can find the links to the examples given in the
slides.

**Text-as-Data articles:**

-   [Nostalgia in European Party Politics: A Text-Based Measurement
    Approach](https://www.cambridge.org/core/journals/british-journal-of-political-science/article/nostalgia-in-european-party-politics-a-textbased-measurement-approach/41C48D60B039F3081EB522FB76646E96)
-   [Does Protest Influence Political Speech? Evidence from UK Climate
    Protest,
    2017–2019](https://www.cambridge.org/core/journals/british-journal-of-political-science/article/does-protest-influence-political-speech-evidence-from-uk-climate-protest-20172019/5C8895ED7EA46C86C2850F44450B9BCD)

**Zeit Online article:**

-   [Acht Minuten Brandmauer, kaum Zeit fürs
    Klima](https://www.zeit.de/politik/deutschland/2025-02/tv-duell-bundestagswahl-merz-scholz-analyse)

**BBC Example:**

-   [BBC Visual and Data Journalism cookbook for R
    graphics](https://bbc.github.io/rcookbook/)
